// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// findmaxgradinregion
NumericVector findmaxgradinregion(int x1, int y1, int areasize, IntegerMatrix print_info);
RcppExport SEXP _fingerprintr_findmaxgradinregion(SEXP x1SEXP, SEXP y1SEXP, SEXP areasizeSEXP, SEXP print_infoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< int >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< int >::type areasize(areasizeSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type print_info(print_infoSEXP);
    rcpp_result_gen = Rcpp::wrap(findmaxgradinregion(x1, y1, areasize, print_info));
    return rcpp_result_gen;
END_RCPP
}
// findcontrast
float findcontrast(int kk, int jj, IntegerMatrix& print_info);
RcppExport SEXP _fingerprintr_findcontrast(SEXP kkSEXP, SEXP jjSEXP, SEXP print_infoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type kk(kkSEXP);
    Rcpp::traits::input_parameter< int >::type jj(jjSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type print_info(print_infoSEXP);
    rcpp_result_gen = Rcpp::wrap(findcontrast(kk, jj, print_info));
    return rcpp_result_gen;
END_RCPP
}
// quality_scores
NumericMatrix quality_scores(IntegerMatrix print_info, IntegerMatrix minutiae_info, bool verbose);
RcppExport SEXP _fingerprintr_quality_scores(SEXP print_infoSEXP, SEXP minutiae_infoSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type print_info(print_infoSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type minutiae_info(minutiae_infoSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(quality_scores(print_info, minutiae_info, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fingerprintr_findmaxgradinregion", (DL_FUNC) &_fingerprintr_findmaxgradinregion, 4},
    {"_fingerprintr_findcontrast", (DL_FUNC) &_fingerprintr_findcontrast, 3},
    {"_fingerprintr_quality_scores", (DL_FUNC) &_fingerprintr_quality_scores, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_fingerprintr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
