# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find the gradient of intensity between the dark and light regions defining a minutiae point.
#'
#' @param x1 X pixel value of a given feature.
#' @param y1 Y pixel value of a given feature.
#' @param print_info Fingerprint image as matrix.
#' @return The maximum gradient within a radius around a given point and the shifted X and Y pixel location values of the pixel in a small neighborhood of the minutiae producing the highest intensity gradient values.
#' @examples
#' print_image <- convert_image(G080_image, "bmp")
#' findmaxgradinregion(841, 541, print_image)
#' @export
findmaxgradinregion <- function(x1, y1, areasize, print_info) {
    .Call(`_fingerprintr_findmaxgradinregion`, x1, y1, areasize, print_info)
}

#' Find an overall contrast of intensity values in the general neighborhood of a minutiae.
#'
#' @param kk X pixel value of a given feature.
#' @param yy Y pixel value of a given feature.
#' @param print_info Fingerprint image as matrix.
#' @return The largest intensity difference between a point and any neighbor intensity in a 3x3 region, divided by the intensity in the print (usually 255).
#' @examples
#' print_image <- convert_image(G080_image, "bmp")
#' findcontrast(831, 542, print_image)
#' @export
findcontrast <- function(kk, jj, print_info) {
    .Call(`_fingerprintr_findcontrast`, kk, jj, print_info)
}

#' Find the quality scores of individual minutiae.
#'
#' @param print_info Fingerprint image as matrix.
#' @param minutiae_info Feature (minutiae) information as matrix
#' @param verbose If TRUE, will output gradient and contrast information in addition to the quality score.
#' @return Matrix containing the columns: x pixel location of minutiae, y pixel location of minutiae, shifted x location, shifted y location, quality score.
#' @examples
#' data(G080_image); data(G080_min)
#' print_image <- convert_image(G080_image, "bmp")
#' min_info <- import_features(G008_min)
#' quality_scores(print_image, min_info)
#' @export
quality_scores <- function(print_info, minutiae_info, verbose = FALSE) {
    .Call(`_fingerprintr_quality_scores`, print_info, minutiae_info, verbose)
}

